import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/core/theme-provider";
import { cn } from "@/lib/utils";

const sfProTextBold = localFont({
  src: "../public/fonts/SF-Pro-Text-Bold.otf",
  variable: "--font-sf-pro-text-bold",
});

const sfProTextRegular = localFont({
  src: "../public/fonts/SF-Pro-Text-Regular.otf",
  variable: "--font-sf-pro-text-regular",
});

const sfProTextLight = localFont({
  src: "../public/fonts/SF-Pro-Text-Light.otf",
  variable: "--font-sf-pro-text-light",
});

const sfProTextMedium = localFont({
  src: "../public/fonts/SF-Pro-Text-Medium.otf",
  variable: "--font-sf-pro-text-medium",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          sfProTextBold.variable,
          sfProTextRegular.variable,
          sfProTextLight.variable,
          sfProTextMedium.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          forcedTheme="light"
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
